config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {sessions: 'users/sessions'}

  namespace :library do
    root 'items#index'
    resources :items do
      collection do
        get 'conferences'
        get 'conf_papers'
        post 'import_conf_papers'
        get 'search'
      end
      member do
        post 'file_upload'
        delete 'file_delete'
      end
    end
  end

root to: redirect('/library')

end

app/models/library.rb
module Library
  def self.table_name_prefix
    'library_'
  end
end

app/models/library/item.rb
require 'elasticsearch/model'


class Library::Item < ActiveRecord::Base
	include AASM

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks


	def as_indexed_json(options={})
#		as_json(only: [:id, :sid, :title, :subtitle, :abstract])
		rez = as_json(
#			methods: [:to_text_test], only: [:id, :sid, :title, :subtitle, :abstract, :to_text_test],
#			only: [:id, :sid, :title, :subtitle, :abstract],
#			include: {
#				item_files: { methods: [:to_text], only: [:to_text] }
#			}
			methods: [:files_to_text], only: [:id, :sid, :title, :subtitle, :abstract, :files_to_text]
#			only: [:id, :sid, :title, :subtitle, :abstract, :to_text_test]
#			only: [:id, :sid, :title, :subtitle, :abstract, :to_text_test], methods: [:to_text_test]
#			only: [:id, :sid, :title, :subtitle, :abstract],
#			include: {
#				item_files: { methods: [:to_text], only: [:to_text] }
#			}
		)
#		puts rez
		rez
	end

#	def to_text_test
#		["rqtqrtqwreqtq", "abrakadabra"]
#	end
	def files_to_text
		item_files.map(&:to_text)
	end

	has_many :item_files, dependent: :destroy
	 #, class_name: "Library::ItemFile", foreign_key: "parent_id", primary_key: "sid", dependent: :destroy
	has_many :children, class_name: "Library::Item", foreign_key: "parent_id", primary_key: "sid", dependent: :destroy
 	belongs_to :parent, class_name: "Library::Item", primary_key: "sid"

#	PTYPES = [:conference, :journal]
	ITEMTYPES = [:folder, :conference, :journal, :conference_paper, :journal_paper]

	validates_uniqueness_of :sid

	aasm do
		state :just_created, initial: true
		state :draft
		state :published
		state :nonexistent
		event :sm_init do
			after do
				#create_new_revision
			end
			#transitions :from => :just_created, :to => :draft
			transitions :from => :just_created, :to => :published
		end
	end


	def self.new_object data
		library_item = Library::Item.new(data)
		if library_item.save
			library_item.sm_init!
			library_item
		else
			nil
		end
	end





	# From Old Mongo

	def self.get_confs_list
		db[:conf].find( {'_meta.class' => "COMS:CONF"} ).sort( [[ '_meta.ctime', -1]] ).inject([]) do |acc,c|
			acc << {'_id' => c['_id'], '_meta' => c['_meta'], 'info' => c['info']}
		end.select{ |c| c['info'] && (c['info']['status']=='active' || c['info']['status']=='archived') }
	end

=begin
	#!!!
	def self.get_paper_files_list cont_id, _id, cl=nil
		@collfiles.find( cl ?
			{'_meta.class' => check_file_class(cl), '_meta.parent' => _id, '_meta.cont_id' => cont_id} :
			{'_meta.parent' => _id, '_meta.cont_id' => cont_id}
		).map do |f|
			get_file_info_from_file f
		end
	end

	#!!!
	def self.check_file_class cn
		case cn.to_s.to_sym
		when :abstract then CONF_PAPER_ABSTRACT_FILE_CLASS
		when :abstract_exdoc then CONF_PAPER_ABSTRACT_EXDOC_FILE_CLASS
		when :paper then CONF_PAPER_PAPER_FILE_CLASS
		when :paper_exdoc then CONF_PAPER_PAPER_EXDOC_FILE_CLASS
		when :presentation then CONF_PAPER_PRESENTATION_FILE_CLASS
	#	when :exdoc then CONF_PAPER_EXDOC_FILE_CLASS
		else 'INEXISTENT'
		end
	end
=end

#	def import_children_from_conference parent, conf_id, papers
	def self.import_children_from_conference parent_item, papers, lang='ru'
		rez = []
		papers.each do |p_id|
			p = Prs::Conf::Paper.get_paper_info p_id
			data = {
				is_dir: false,
				parent: parent_item,
				item_type: :conference_paper,
				title: p['text']['title'][lang],
#				subtitle: p['authors'] ? p['authors'].map{ |a| {fname: a['fname'][lang], mname: a['mname'][lang], lname: a['lname'][lang] } } : [],
				subtitle: p['authors'] ?
					p['authors'].map{ |a| a['fname'][lang] + ' ' + a['mname'][lang] +' '+ a['lname'][lang] }.join(', ') :
					[],
				abstract: p['text']['abstract'][lang]
			}
			item = new_object data

			if p['files']
				p['files'].each do |f|
					if f[:class_code]=='paper' && lang==f[:_meta]['lang']
						rez << item.sid
						fdata = Prs::Conf::Paper.get_paper_file p_id, lang, 'paper'
				        if fdata
							src = StringIO.new(fdata.data)
							class << src; attr_accessor :original_filename; end
							src.original_filename = fdata.filename
				        	f = item.item_files.create(file: src, file_type: :paper)
				        	item.save!
				        end
					end
				end
			end
		end
		rez
	end
	def self.import_whole_conference parent_item, conf_id, lang='ru'
		c = Prs::Conf::Conf.get_conf_info conf_id
#		puts "!!!!!!!!!!!!!!"
#		puts c
			data = {
				is_dir: true,
				parent: parent_item,
				item_type: :conference,
				title: c['title'][lang],
				subtitle: '',
				abstract: c['description'][lang]
			}
			item = new_object data
			list = Prs::Conf::Paper.get_conf_papers_list conf_id
			papers = list.map(){|p| p['_id']}
#			papers = list.map(:_id)
			import_children_from_conference item, papers, lang

	end

	def self.db
		Mongoid::Clients.default
	end


end


#Library::Item.import

app/models/library/item_file.rb
class Library::ItemFile < ActiveRecord::Base
	include AASM

  belongs_to :item
  mount_uploader :file, ::LibraryItemFileUploader

	FILETYPES = [:paper, :abstract, :presentation]

	aasm do
		state :just_created, initial: true
	end

	def to_text
#		t = Yomu.new(file.current_path).text rescue ""
#		t
		""
	end

end

app/controllers/library/items_controller.rb
class Library::ItemsController < ApplicationController
  before_action :set_library_item, only: [:show, :edit, :update, :destroy, :file_upload, :file_delete]
  before_action :set_parent_item

  # GET /library/items
  # GET /library/items.json
  def index
    #@library_items = Library::Item.all
    @library_item = nil
#    show
    get_items
    @confs_list = Library::Item.get_confs_list
    @can_edit = current_user && current_user.is_admin
    render :show
  end

  # GET /library/items/1
  # GET /library/items/1.json
  def show
    get_items @library_item
    @library_item_files = @library_item ? @library_item.item_files : []
    @library_item_file = @library_item ? Library::ItemFile.new( {item: @library_item} ) : nil

    @confs_list = Library::Item.get_confs_list

    @can_edit = current_user && current_user.is_admin
#    @can_edit = false
#    @can_edit = true
  end

  def search
    @search_query = params['q']
#    response = Library::Item.search @search_query
#    response = Library::Item.search query: { match:  { title: @search_query } }
    response = Library::Item.search({query:
          {
            bool: {
              should: [
                {
                  multi_match: {
                    query: @search_query,
#                    fields: ['title^3', 'subtitle^2', 'abstract'],
#                    fields: ['title^3', 'subtitle^2', 'abstract', 'item_files.to_text', 'to_text_test'],
                    fields: ['title^10', 'subtitle^7', 'abstract^5', 'files_to_text'],
                    operator: 'and',
                    #analyzer: 'russian_morphology_custom'
                  }
                }
              ]
            }
          }
        }, size: 100)

#    @search_records = response.records
    @library_items = response.records
#    puts records
  end


  # GET /library/items/new
  def new
    @can_edit = current_user && current_user.is_admin
#    @can_edit = false
    unless @can_edit
      redirect_to @parent_item ? @parent_item : library_root_path
      return
    end
  #    @library_item = Library::Item.new
  #    @library_item = Library::Item.new( @parent_item ? {parent: @parent_item.sid} : {} )
      @library_item = Library::Item.new( @parent_item ? {parent: @parent_item} : {} )
  end

  # GET /library/items/1/edit
  def edit
    @can_edit = current_user && current_user.is_admin
#    @can_edit = false
    unless @can_edit
      redirect_to @library_item
      return
    end
  end

  def file_upload
    @can_edit = current_user && current_user.is_admin
#    @can_edit = false
    if @can_edit
      @library_item_file = @library_item ? Library::ItemFile.new( {item: @library_item} ) : nil
      data = params[:library_item_file]
      if data
        file_type = data[:file_type] || 'paper'
        file = data[:file]
        if file
          f = @library_item.item_files.create(file: file, file_type: file_type)
          f.save!
          @library_item.save!
        end
      end
    end

    @library_item_files = @library_item ? @library_item.item_files : []
    respond_to do |format|
      format.js { }
#      format.html { }
#      format.json { }
    end

  end

  def file_delete
    @can_edit = current_user && current_user.is_admin
#    @can_edit = false
    if @can_edit
      item_file_id = params[:item_file]
      item_file = @library_item.item_files.where({sid: item_file_id}).first
      item_file.destroy
    end

    @library_item_files = @library_item ? @library_item.item_files : []
    respond_to do |format|
        format.js { }
#        format.html { }
#        format.json { }
    end
  end


  # POST /library/items
  # POST /library/items.json
  def create
    @can_edit = current_user && current_user.is_admin
#    @can_edit = false
    respond_to do |format|
      unless @can_edit
        format.html { redirect_to library_items_url, notice: "You can't create new item" }
        format.json { head :no_content }
      else
        @library_item = Library::Item.new(library_item_params.merge({}))
        if @library_item.save
          @library_item.sm_init!
          format.html { redirect_to @library_item, notice: 'Item was successfully created.' }
          format.json { render :show, status: :created, location: @library_item }
        else
          format.html { render :new }
          format.json { render json: @library_item.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /library/items/1
  # PATCH/PUT /library/items/1.json
  def update
    @can_edit = current_user && current_user.is_admin
#    @can_edit = false
    respond_to do |format|
      unless @can_edit
        format.html { redirect_to @library_item, notice: "You can't change it" }
        format.json { head :no_content }
      else
        if @library_item.update(library_item_params)
          format.html { redirect_to @library_item, notice: 'Item was successfully updated.' }
          format.json { render :show, status: :ok, location: @library_item }
        else
          format.html { render :edit }
          format.json { render json: @library_item.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /library/items/1
  # DELETE /library/items/1.json
  def destroy
    @can_edit = current_user && current_user.is_admin
#    @can_edit = false
    parent = @library_item.parent
    respond_to do |format|
      unless @can_edit
        format.html { redirect_to @library_item, notice: "You can't delete it" }
        format.json { head :no_content }
      else
        @library_item.destroy
#       format.html { redirect_to library_items_url, notice: 'Item was successfully destroyed.' }
        format.html { redirect_to parent || library_items_url, notice: 'Item was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end



  def conferences
    respond_to do |format|
      format.js {}
    end
  end

  def conf_papers
    @conf_id = params['conf_id']
    @library_item_id = params['library_item']
#    @papers_list = Library::Item.get_conf_papers_list @conf_id
    @papers_list = Prs::Conf::Paper.get_conf_papers_list @conf_id
    respond_to do |format|
      format.js {}
    end
  end

  def import_conf_papers
    @library_item_id = params['library_item']
    @library_item = Library::Item.find(@library_item_id)
    papers = params['papers']
    conf_id = params['conf_id']
    lang = params['lang']
    if papers
      Library::Item.import_children_from_conference @library_item, papers, lang
    elsif conf_id
      Library::Item.import_whole_conference @library_item, conf_id, lang
    end
    get_items @library_item
    respond_to do |format|
      format.js {}
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_library_item
      @library_item = Library::Item.find(params[:id])
      current = @library_item
      @library_item_ancestors = []
      while current do
        @library_item_ancestors.unshift current
        current = current.parent
      end
    end
    def set_parent_item
      @parent_item = nil
      parent_id = params[:parent]
#      puts "!!!!!!!!!!!!!!!!!!!!!!"
#      puts parent_id
      if parent_id
        @parent_item = Library::Item.find(parent_id)
      end
#      puts @parent_item
#      puts params
#      puts "!!!!!!!!!!!!!!!!!!!!!!"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def library_item_params
#      params.require(:library_item).permit(:sid, :parent, :aasm_state, :position, :is_dir, :item_type, :title, :subtitle, :abstract, :children_seq)
#      params.require(:library_item).permit(:is_dir, :parent, :item_type, :title, :subtitle, :abstract)
      params.require(:library_item).permit(:is_dir, :parent_id, :item_type, :title, :subtitle, :abstract)
    end

    def get_items parent=nil
      @library_items = parent.nil? ? Library::Item.where({parent: nil}) : parent.children.all
#      @library_items = parent.nil? ? Library::Item.all : parent.children.all
#      @library_items = parent.nil? ? Library::Item.all : parent.is_dir ? parent.children.all : []
#      @library_items = Library::Item.all
    end

end

app/helpers/library/items_helper.rb
module Library::ItemsHelper
end

app/views/library/items/_conf_papers_list.html.erb
<%#= @papers_list.map{ |p| %w[en ru].map{ |lang| p['text']['title'][lang] }.join(" | ") }.inspect %>


<%= form_tag import_conf_papers_library_items_path(library_item: @library_item_id), method: :post, remote: true do %>
            <div class="list-group">
              <% @papers_list.each do |p| %>
                <% if p['text'] && p['text']['title'] %>
                  <%#= link_to "#", class: "list-group-item" do %>
                  <div class="list-group-item">
                    <p class="list-group-item-text">
	                    <%= check_box_tag(:'papers[]', p['_id'], false, class: 'papers_list_checkbox') %>
                    	<%= %w[en ru].map { |lang| p['text']['title'][lang].to_s }.join(' | ') %>
                    </p>
                   </div>
                  <%# end %>
                <% end %>
              <% end %>
            </div>


<div class="form-group">
<%= label_tag 'select_deselect_all', classs: 'category_select', class: "form-control" do %>
	<%= t('library.item.show.modal.select_all') %> <%= check_box_tag('select_deselect_all', 1) %>
<% end %>
<%= select_tag :lang, options_for_select([:en, :ru]), class: "form-control" %>
</div>

<div class="form-group">
<%= submit_tag t('library.item.show.modal.import_selected'), class: "btn btn-primary" %>
</div>

<% end %>

<script type="text/javascript">
	var flag = true;
//	alert("loaded");
//$('#importItemsModal').on('shown.bs.modal', function() {
$('#select_deselect_all').on('change', function() {
	$('.papers_list_checkbox').prop("checked", $(this).is(":checked"));
});
</script>

app/views/library/items/_files_list.html.erb
      <%= content_tag_for(:div, @library_item_files) do |item_file| %>
        <div class="list-group-item">
        <%= link_to item_file.file.url, target: '_blank', cclass: "list-group-item" do %>
          <span class="glyphicon glyphicon-save"></span>
          <%= item_file.file_type %>
        <% end %>
              <%= link_to file_delete_library_item_path(@library_item, item_file: item_file.sid), remote: true, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-link btn-sm bbtn-danger pull-right' do %>
                [&times;]
              <% end if @can_edit %>
        </div>
      <% end %>

app/views/library/items/_show_children_list.html.erb
      <%= content_tag_for(:div, @library_items) do |item| %>
  <div class="list-group-item">
    <h4 class="list-group-item-heading">
      <%= link_to library_item_path item do %>
        <span class="glyphicon glyphicon-<%= item.is_dir ? 'folder-close' : 'file' %>"></span>
        <%= item.title %>
      <% end %>
    </h4>
    <p class="list-group-item-text"><%= item.subtitle %></p>
    <!--p class="list-group-item-text"><%= item.abstract %></p-->
    <!--p class="list-group-item-text"><%#= link_to 'Admin', edit_ws_process_path(ws_process), :cclass => 'btn btn-success' %></p-->
  </div>
      <% end %>

app/views/library/items/edit.html.erb
<div class="page-header">
  <%= link_to library_items_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    <%= t('library.item.edit.back_btn') %>
  <% end %>
  <%= link_to @library_item, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    <%= t('library.item.edit.show_btn') %>
  <% end %>
  <h1><%= t('library.item.edit.title') %></h1>
</div>

<%= render 'form' %>

app/views/library/items/file_delete.js.erb
<% if @can_edit %>
	//alert('success!');
	$('#lib-item-files-list').html("<%= escape_javascript render('files_list') %>");
<% end %>

app/views/library/items/index.html.erb
<%#= render template: 'items/show' %>


<!-- div class="page-header">
  <%= link_to new_library_item_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Item
  <% end %>
  <h1>Listing library_items</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Sid</th>
            <th>Parent</th>
            <th>Aasm state</th>
            <th>Position</th>
            <th>Item type</th>
            <th>Title</th>
            <th>Subtitle</th>
            <th>Abstract</th>
            <th>Children seq</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @library_items) do |library_item| %>
            <td><%= library_item.sid %></td>
            <td><%= library_item.parent %></td>
            <td><%= library_item.aasm_state %></td>
            <td><%= library_item.position %></td>
            <td><%= library_item.item_type %></td>
            <td><%= library_item.title %></td>
            <td><%= library_item.subtitle %></td>
            <td><%= library_item.abstract %></td>
            <td><%= library_item.children_seq %></td>
            <td><%= link_to 'Show', library_item %></td>
        <td><%= link_to 'Edit', edit_library_item_path(library_item) %></td>
        <td><%= link_to 'Destroy', library_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div -->

app/views/library/items/new.html.erb
<div class="page-header">
  <%= link_to library_items_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    <%= t('library.item.new.back_btn') %>
  <% end %>
  <h1><%= t('library.item.new.title') %></h1>
</div>

<%= render 'form' %>

app/views/library/items/search.html.erb
  <div class="ppage-header text-center">
    <h1 class=""><%= "#{t('library.search.results_for')} #{@search_query}" %></h1>
  </div>


<section>

<div class="list-group lib-item-children" id="children_list">
<%#= render 'show_children_list' %>



	<% @library_items.each_with_hit do |item, hit| %>
  <div class="list-group-item">
    <h4 class="list-group-item-heading">
      <%= link_to library_item_path item do %>
        <span class="glyphicon glyphicon-<%= item.is_dir ? 'folder-close' : 'file' %>"></span>
        <%= item.title %>
      <% end %>
    </h4>
    <p class="list-group-item-text"><%= item.subtitle %></p>
    <!--p class="list-group-item-text"><%= item.abstract %></p-->
    <!--p class="list-group-item-text"><%#= link_to 'Admin', edit_ws_process_path(ws_process), :cclass => 'btn btn-success' %></p-->
    <div class="list-group-item-text small"><b><%= hit._score %></b></div>
  </div>
	<% end %>



</div>


</section>

app/views/library/items/show.html.erb
<% if @library_item %>
  <% if @can_edit %>
  <div class="btn-block text-right">
    <%= link_to @library_item.parent ? library_item_path(@library_item.parent) : library_root_path, class: 'btn btn-default' do %>
      <span class="glyphicon glyphicon-list-alt"></span>
      <%= t('library.item.show.back_btn') %>
    <% end if false %>
    <%= link_to edit_library_item_path(@library_item), class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-pencil"></span>
      <%= t('library.item.show.edit_btn') %>
    <% end %>
    <%= link_to @library_item, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' do %>
      <span class="glyphicon glyphicon-trash"></span>
      <%= t('library.item.show.delete_btn') %>
    <% end %>
  </div>
  <% end %>

  <div class="ppage-header text-center">
    <h1 class=""><%= @library_item.title %></h1>
    <!-- small><%= @library_item.subtitle %></small-->
    <div class="lib-item-subtitle"><%= @library_item.subtitle %></div>
    <div class="lib-item-abstract text-justify"><%= @library_item.abstract %></div>
  </div>


  <% if !@library_item.nil? && !@library_item.is_dir %>
  <div class="panel panel-default lib-item-files">
    <div class="panel-heading"><h3>Files</h3></div>
    <div class="list-group llib-item-files" id="lib-item-files-list">
      <%= render 'files_list' %>
    </div>

    <div class="panel-body">

      <% if @library_item_file && @can_edit %>
        <div class="lib-item-file-form">
        <h4>Add file</h4>
          <%= form_for @library_item_file, url: file_upload_library_item_path(@library_item), remote: true, html: { class: "form-horizontal", role: "form", multipart: true } do |f| %>
            <div class="form-group">
              <%= f.label :file_type, :class => "col-sm-2 control-label" %>
              <div class="col-sm-10">
                <%= f.select :file_type, options_for_select(Library::ItemFile::FILETYPES, @library_item_file.file_type), :class => "form-control" %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :file, :class => "col-sm-2 control-label" %>
                <div class="col-sm-10">
              <%= f.file_field :file, :class => "form-control" %>
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <%= f.submit class: "btn btn-primary" %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>

    </div>
  </div>
  <% end %>

<% end %>



<% if !@library_items.empty? || !@library_item.nil? && @library_item.is_dir || @library_item.nil? %>
<!-- hr-->

<section>

<% if @can_edit %>
<div class="btn-block text-right">
  <%= link_to new_library_item_path(@library_item ? {parent: @library_item.sid} : {}), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    <%= t('library.item.show.new_item') %>
  <% end %>
  <%= link_to("javascript:;", class: 'btn btn-primary', "data-toggle": "modal", "data-target": "#importItemsModal") do %>
    <span class="glyphicon glyphicon-import"></span>
    <%= t('library.item.show.import_papers') %>
  <% end %>
  <%= link_to("javascript:;", class: 'btn btn-primary', "data-toggle": "modal", "data-target": "#importItemsModal2") do %>
    <span class="glyphicon glyphicon-import"></span>
    <%= t('library.item.show.import_conference') %>
  <% end %>
</div>

<!-- Modal -->
<div class="modal fade" id="importItemsModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">
          <%= t('library.item.show.modal.title') %>
        </h4>
      </div>
      <div class="modal-body" id="importItemsBody">
        <div class="row">
          <div class="col-sm-6 left-column" id="importItemsConfs">
            <div class="list-group">
              <% @confs_list.each do |c| %>
                <% if c['info'] && c['info']['title'] %>
                  <%= link_to conf_papers_library_items_path(library_item: (@library_item ? @library_item.sid : nil),  conf_id: c['_id']), remote: true, id: 'conf_'+c['_id'], class: "list-group-item" do %>
                    <p class="list-group-item-text">
                      <%= %w[en ru].map { |lang| c['info']['title'][lang].to_s }.join(' | ') %>
                    </p>
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>
          <div class="col-sm-6 right-column" id="importItemsPapers">
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">
          <%= t('library.item.show.modal.close') %>
        </button>
        <!--button type="button" class="btn btn-primary">Save changes</button-->
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="importItemsModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel2">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
<%= form_tag import_conf_papers_library_items_path(library_item: (@library_item ? @library_item.sid : nil)), method: :post, remote: true do %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel2">
          <%= t('library.item.show.modal2.title') %>
        </h4>
      </div>
      <div class="modal-body2" id="importItemsBody2">
        <div class="rrow">
          <div class="ccol-sm-6 left-column" id="importItemsConfs2">
            <div class="list-group">
              <% @confs_list.each do |c| %>
                <% if c['info'] && c['info']['title'] %>
                  <%#= link_to conf_papers_library_items_path(library_item: (@library_item ? @library_item.sid : nil),  conf_id: c['_id']), remote: true, id: 'conf_'+c['_id'], class: "list-group-item" do %>
                    <p class="list-group-item list-group-item-text">
                      <%= radio_button_tag(:'conf_id', c['_id'], false, class: 'confs_list_radio_button') %>
                      <%= %w[en ru].map { |lang| c['info']['title'][lang].to_s }.join(' | ') %>
                    </p>
                  <%# end %>
                <% end %>
              <% end %>
            </div>
          </div>
          <!--div class="col-sm-6 right-column" id="importItemsPapers">
          </div-->
        </div>
      </div>
      <div class="modal-footer">

<div class="form-group">
<%= select_tag :lang, options_for_select([:en, :ru]), class: "form-control" %>
</div>

        <%= submit_tag t('library.item.show.modal2.import_selected'), class: "btn btn-primary" %>
        <button type="button" class="btn btn-default" data-dismiss="modal">
          <%= t('library.item.show.modal2.close') %>
        </button>
        <!--button type="button" class="btn btn-primary">Save changes</button-->
      </div>
<% end %>
    </div>
  </div>
</div>



<% end %>


<div class="list-group lib-item-children" id="children_list">
<%= render 'show_children_list' %>
</div>


</section>

<% end %>