config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {sessions: 'users/sessions'}

  namespace :library do
    root 'items#index'
    resources :items do
      collection do
        get 'conferences'
        get 'conf_papers'
        post 'import_conf_papers'
        get 'search'
      end
      member do
        post 'file_upload'
        delete 'file_delete'
      end
    end
  end

root to: redirect('/library')

end

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-69944829-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_yandex_metrika.html.erb
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter33501943 = new Ya.Metrika({
                    id:33501943,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true,
                    webvisor:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/33501943" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Comsep Library</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <%= render partial: 'layouts/yandex_metrika' %>
  <%#= render partial: 'layouts/google_analytics' %>

</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container ccontainer-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%#= link_to t('layouts.application.project_name'), "/", class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to root_path do %>
            <span class="glyphicon glyphicon-home"></span> <%= t('layouts.application.home') %>
          <% end %></li>
          <li class="active"><%= link_to library_root_path do %>
            <span class="glyphicon glyphicon-book"></span> <%= t('layouts.application.library') %>
          <% end %></li>
        </ul>


        <!--div class="nnav nnavbar-nav navbar-right"-->
        <ul class="nav navbar-nav navbar-right" sstyle="vertical-align: middle; padding-right: 20px;">

          <% if user_signed_in? %>
            <li><a href="<%#= profile_path(current_user) %>"><%#= t('journal.nav.my_profile') %>
              <!--span>&nbsp;</span--><!--i class="fa fa-user fa-lg fa-fw"></i-->
              <span class="glyphicon glyphicon-user"></span> <%= current_user.full_name %></a></li>
            <li>
              <%= link_to(destroy_user_session_path, :method => :delete) do %>
                <span class="glyphicon glyphicon-log-out"></span> <%= t('layouts.application.logout') %>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to(new_user_session_path) do %>
                <span class="glyphicon glyphicon-log-in"></span> <%= t('layouts.application.login') %>
              <% end %>
            </li>
          <% end %>
            <li>
              <%= link_to("https://elplib.freshdesk.com/", ttarget: '_blank') do %>
                <span class="glyphicon glyphicon-exclamation-sign"></span> <%= t('layouts.application.helpdesk') %>
              <% end %>
            </li>
        </ul>


        <form action="<%= search_library_items_path() %>" class="navbar-form navbar-right   nnav nnavbar-nav" role="search" style="mmargin: auto; padding: 0;">
          <div class="form-group hhas-success has-feedback">
            <input name="q" type="text" class="form-control" placeholder="<%= t('layouts.application.search') %>" value="<%= @search_query ? @search_query : '' %>">
            <span class="glyphicon glyphicon-search  form-control-feedback"></span>
          </div>
        </form>
        <!--/div-->




      </div>
    </div>
  </nav>


  <div class="container ccontainer-fluid">
    <ol class="breadcrumb">
      <li><%= link_to t('library.root'), library_root_path %></li>
      <% @library_item_ancestors.each do |item| %>
        <li><%= link_to item.title, library_item_path(item) %></li>
      <% end if @library_item_ancestors %>
      <% if @search_query %>
        <li><%= link_to "#{t('library.search.results_for')} #{@search_query}", search_library_items_path(q: @search_query) %></li>
      <% end %>
    </ol>
  </div>


  <div class="container ccontainer-fluid">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>